{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gargle
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gargle_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gargle/gargle_{{ version }}.tar.gz
  sha256: 8e0f1edf5595d4fd27bd92f98af1cc0c1349975803d9d6f3ff0c25ee2440498b

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli >=3.0.0
    - r-fs >=1.3.1
    - r-glue >=1.3.0
    - r-httr >=1.4.0
    - r-jsonlite
    - r-lifecycle
    - r-openssl
    - r-rappdirs
    - r-rlang >=1.0.0
    - r-rstudioapi
    - r-withr
  run:
    - r-base
    - r-cli >=3.0.0
    - r-fs >=1.3.1
    - r-glue >=1.3.0
    - r-httr >=1.4.0
    - r-jsonlite
    - r-lifecycle
    - r-openssl
    - r-rappdirs
    - r-rlang >=1.0.0
    - r-rstudioapi
    - r-withr

test:
  commands:
    - $R -e "library('gargle')"           # [not win]
    - "\"%R%\" -e \"library('gargle')\""  # [win]

about:
  home: https://gargle.r-lib.org
  dev_url: https://github.com/r-lib/gargle
  license: MIT
  summary: Provides utilities for working with Google APIs <https://developers.google.com/apis-explorer>.  This includes functions and classes for handling common credential types and for preparing, executing, and processing HTTP requests.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Date/Publication: 2019-07-26 19:40:02 UTC
