travis:
  secure:
    BINSTAR_TOKEN: aVsmMY4yPsdLhWwykugadsgo0yV76spA3NoDEn7SLUzWUW1emeGMsyN4Bud0M+FrzjJJSuFXyYQ0EhNBuIjPLwL/lhEHmrVp6pyq57cosgRDMPDxIgeqFF2qQDNgXqrflAGA3W1hWyv9M/CP6uNx/u+hzlqtF4qShlKXqgzIhX8BJQOAyLiVn3R9fnpUQm2RKcDlEsAa+d9oezOm1s1cff9fv6ndqcKTxmnzvv/gDmhJr62AXMccjF4itrySgx7Aj1tW7NsCcZbnBAMDah8a+9wN5bz8mmBmlW5yJ2JohstXYpvx3nB32U3d5WTXNCCgJAaypXe7RIieypkqZ/c2sywE/Ti9dmXG3tbw69aS2szjIVYec5JFszx6ALMJb15snwdLXHMd2smugDepy7oaRIStggSUwwHjXXgNHnKQkYieCB7R7NQqlro1ixsWFuHS/qJprrKt0lF87wikQ71+oDgWd8ApfnfdwCnBueCTyeEb+PbPbAq6jpliGwkM2QkQc38CDQpu3xj3fN4JOsTIL/SblxMjDyq9H6GgQ5UQ+S2YfZC62b/8Prl4XbEBzjdjRmxrjUxGakBihZr/9n+7L2FO/qRnrZfN8syCILms8qki4kSrVaL3Oy5W4RpNmNVQ8RzKEpuKu42UCS5t33V1pYlumpmBefmwrX9wMui2MI8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
