appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: L988zoDvgtZJ0EHRSpqGYZzvckmr/WhSRjs7HUa8YrlOpNypRB5A71ljqvtHqPR1/dDzcCPyQ73w3kWYFx6SRHgOkSu20T/bEFd9O9Cp1CACVVckDpFb9IPd4wrVOLwDjAF6j2NCOBbAJao43se0xdjYbWOwtvJcTnKdRU78uXEucLNvVz5J9JmQrdeGG5MGv5z84BVXZwgGoY75vSfznu+iJ2J1kc1D7DyZf+mKC6QKO5D8hnspucG3Xh05YJLQO9AhXUikPqzr80nE3kPcwT84VlwS/OgFP0qcl+gQsMp3qahh6EsvBwlsrB+uRSoN0Z87PFiQPmWrkY7dhWr2EdF/E/aGf/UN6El4lcftv4X2OL2YPsxmgrqgAAQbaCoU854g3kkPZNkw+JoyLe9AwSu0Zbi+lah5iPnKx3Yx/91EjxBbXOb9xRcP9I6YHmqn4Z2/bClkqoz1ocwexUPqn6mrx8OrClKYnmfQdjGSG4AHpWzdVKSFzu0AQI6eibZQR4yGfi5nMawc8mcr5SACgW/8TCgGyqLsxf1EoeScCEHQ00F4PWJJGQzM6qTCgKi6UkvZvx9tfoSrA6nw95hPvI0jnjies7rEhA8+aDYaCYmxFmBd311Aqief7fkM7RbtbJ5rJ9frLeTGi2CplmQHPFmE/oD4f3zMcOD2bFGJKqE=
